name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths:
      - feature-a
  pull_request:
    branches: [ "main" ]
    paths:
      - feature-a

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag tfrank773/feature-a:1.0.0
