name: feature-a-build

on:
  push:
    branches: [ "main" ]
    paths:
      - 'feature-a/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'feature-a/**'

jobs:
  call-docker-build-and-push-workflow:
    uses: franktylerva/github-workflows/.github/workflows/docker-build-and-push.yml@main
    with:
      context: "./feature-a"
      image-tags: tfrank773/feature-a:1.0.1
    secrets: inherit