name: feature-b-build

on:
  push:
    branches: [ "main" ]
    paths:
      - 'feature-b/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'feature-b/**'

jobs:
  call-docker-build-and-push-workflow:
    uses: franktylerva/github-workflows/.github/workflows/docker-build-and-push.yml@main
    with:
      context: "./feature-b"
      image-name: feature-b
    secrets: inherit