name: feature-a-build

on:
  push:
    branches: [ "main" ]
    paths:
      - 'feature-a/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'feature-a/**'

env:
  REGISTRY: docker.io
  IMAGE_NAME: tfrank773/feature-a

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_SECRET }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: "./feature-a"
          platforms: linux/amd64,linux/arm64
          push: true
          tags: tfrank773/feature-a:1.0.0
