name: test

on:
  workflow_dispatch

env:
  TAGS: "a,b,c"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: |
          tags=($(echo "$TAGS" | tr ',' '\n'))
          echo "${tags[0]}"
