name: test

on:
  workflow_dispatch

env:
  TAGS: "{tags: ['a','b','c'], name: 'cool'}"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo ${{ toJson(env.TAGS).name }}
