apiVersion: apps/v1
kind: Deployment
metadata:
  name: micro-frontend
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: micro-frontend
  template:
    metadata:
      labels:
        app: micro-frontend
    spec:
      initContainers:
      - name: feature-a
        image: feature-a:1.0.0
        volumeMounts:
        - name: shared-data
          mountPath: /shared-data
        command: ["/bin/sh", "-c", "cp -r /feature-a /shared-data/feature-a"]
      containers:
      - name: nginx
        image: nginx
        volumeMounts:
        - name: shared-data
          mountPath: /usr/share/nginx/html
        ports:
        - containerPort: 80